spring:
  application:
  name: cloudinaryDemo
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
cloud:
  aws:
    credentials:
      access-key: <Access-Key>
      secret-key: <Secret-Key>

    region:
      static:
        name: us-east-1
application:
  bucket:
    name: my-app-storage-123
